# fly.toml app configuration file generated for rails-blog-1 on 2023-05-10T11:08:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-blog-1"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
